// <auto-generated />
using System;
using BackendApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250814072956_grade-calculation")]
    partial class gradecalculation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Core.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("CalculatedGrade")
                        .HasColumnType("float");

                    b.Property<double?>("MainGrade")
                        .HasColumnType("float");

                    b.Property<int>("StudentSubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentSubjectId")
                        .IsUnique();

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("BackendApi.Core.GradeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.ToTable("GradeItems");
                });

            modelBuilder.Entity("BackendApi.Core.Models.ClassStanding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attendance")
                        .HasColumnType("int");

                    b.Property<decimal>("Average")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClassStandingPercentage")
                        .HasColumnType("int");

                    b.Property<int?>("MidtermGradeId")
                        .HasColumnType("int");

                    b.Property<decimal>("PG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Recitation")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MidtermGradeId");

                    b.ToTable("ClassStanding");
                });

            modelBuilder.Entity("BackendApi.Core.Models.Dto.UserEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserEvents");
                });

            modelBuilder.Entity("BackendApi.Core.Models.GradePointEquivalent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GradePoint")
                        .HasColumnType("float");

                    b.Property<double>("MaxPercentage")
                        .HasColumnType("float");

                    b.Property<double?>("MinPercentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("GradePointEquivalents");
                });

            modelBuilder.Entity("BackendApi.Core.Models.MidtermQuizList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MidtermGradeId")
                        .HasColumnType("int");

                    b.Property<decimal>("PG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuizPercentage")
                        .HasColumnType("int");

                    b.Property<int>("QuizScore")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuizScore")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MidtermGradeId");

                    b.ToTable("MidtermQuizLists");
                });

            modelBuilder.Entity("BackendApi.Core.Models.StudentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestTransaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("YearLevel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("StudentModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BackendApi.Core.Models.StudentSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentID");

                    b.HasIndex("SubjectID");

                    b.ToTable("StudentSubjects");
                });

            modelBuilder.Entity("BackendApi.Core.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("BackendApi.Core.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("BackendApi.Core.Models.MidtermGrade", b =>
                {
                    b.HasBaseType("BackendApi.Core.Models.StudentModel");

                    b.Property<int>("Average")
                        .HasColumnType("int");

                    b.Property<double>("GradePointEquivalent")
                        .HasColumnType("float");

                    b.Property<int>("MidtermGradeScore")
                        .HasColumnType("int");

                    b.Property<int>("MidtermGradeTotalSCore")
                        .HasColumnType("int");

                    b.Property<int>("PercentageOfMidtermAndPrelim")
                        .HasColumnType("int");

                    b.Property<int>("PrelimGrade")
                        .HasColumnType("int");

                    b.Property<int>("PrelimGradeTotalScore")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectScore")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectScorePercentage")
                        .HasColumnType("int");

                    b.Property<int?>("SEPPercentage")
                        .HasColumnType("int");

                    b.Property<int?>("SEPSCore")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalMidtermGrade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalScorePerlimAndMidterm")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("MidtermGrade");
                });

            modelBuilder.Entity("BackendApi.Core.Grade", b =>
                {
                    b.HasOne("BackendApi.Core.Models.StudentSubject", "StudentSubject")
                        .WithOne("Grade")
                        .HasForeignKey("BackendApi.Core.Grade", "StudentSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentSubject");
                });

            modelBuilder.Entity("BackendApi.Core.GradeItem", b =>
                {
                    b.HasOne("BackendApi.Core.Grade", "Grade")
                        .WithMany("GradeItems")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("BackendApi.Core.Models.ClassStanding", b =>
                {
                    b.HasOne("BackendApi.Core.Models.MidtermGrade", null)
                        .WithMany("ClassStandings")
                        .HasForeignKey("MidtermGradeId");
                });

            modelBuilder.Entity("BackendApi.Core.Models.Dto.UserEvent", b =>
                {
                    b.HasOne("BackendApi.Core.Models.StudentModel", "User")
                        .WithMany("UserEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendApi.Core.Models.MidtermQuizList", b =>
                {
                    b.HasOne("BackendApi.Core.Models.MidtermGrade", null)
                        .WithMany("MidtermQuizzesLists")
                        .HasForeignKey("MidtermGradeId");
                });

            modelBuilder.Entity("BackendApi.Core.Models.StudentSubject", b =>
                {
                    b.HasOne("BackendApi.Core.Models.StudentModel", "User")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApi.Core.Models.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendApi.Core.Models.Subject", b =>
                {
                    b.HasOne("BackendApi.Core.Models.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BackendApi.Core.Models.Teacher", b =>
                {
                    b.HasOne("BackendApi.Core.Models.StudentModel", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendApi.Core.Grade", b =>
                {
                    b.Navigation("GradeItems");
                });

            modelBuilder.Entity("BackendApi.Core.Models.StudentModel", b =>
                {
                    b.Navigation("StudentSubjects");

                    b.Navigation("UserEvents");
                });

            modelBuilder.Entity("BackendApi.Core.Models.StudentSubject", b =>
                {
                    b.Navigation("Grade");
                });

            modelBuilder.Entity("BackendApi.Core.Models.Subject", b =>
                {
                    b.Navigation("StudentSubjects");
                });

            modelBuilder.Entity("BackendApi.Core.Models.Teacher", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("BackendApi.Core.Models.MidtermGrade", b =>
                {
                    b.Navigation("ClassStandings");

                    b.Navigation("MidtermQuizzesLists");
                });
#pragma warning restore 612, 618
        }
    }
}
